version = 1
SPDX-PackageName = "ExploitUtils"
SPDX-PackageSupplier = "https://github.com/cod3ddot/nibblet"

[[annotations]]
path = [
    ".env",
    ".env.example",
    ".github/workflows/**",
    "src/lib/exploits/schemas/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "bun.lock",
    "package.json",
    "tsconfig.json",
    ".prettierrc.json",
    ".gitattributes",
    ".eslintrc.json",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["assets/fonts/Poppins/**"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2020 The Poppins Project Authors (https://github.com/itfoundry/Poppins)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "CC-BY-SA-4.0"
